//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorksCoreLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtWorksCoreLib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build notifications from Go has yet to be implemented..
        /// </summary>
        public static string BuildNotification {
            get {
                return ResourceManager.GetString("BuildNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or empty.
        /// </summary>
        public static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to see that you are not using HTTPS on an HTTP connection or vise versa..
        /// </summary>
        public static string CannotInterpretResponse {
            get {
                return ResourceManager.GetString("CannotInterpretResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CardCreatedByLogin {
            get {
                return ResourceManager.GetString("CardCreatedByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CardCreatedByName {
            get {
                return ResourceManager.GetString("CardCreatedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CardCreatedOn {
            get {
                return ResourceManager.GetString("CardCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CardDescription {
            get {
                return ResourceManager.GetString("CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CardId {
            get {
                return ResourceManager.GetString("CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string CardModifiedBy {
            get {
                return ResourceManager.GetString("CardModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string CardModifiedByLogin {
            get {
                return ResourceManager.GetString("CardModifiedByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string CardModifiedByName {
            get {
                return ResourceManager.GetString("CardModifiedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string CardModifiedOn {
            get {
                return ResourceManager.GetString("CardModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card could not be found:.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id.
        /// </summary>
        public static string CardProjectId {
            get {
                return ResourceManager.GetString("CardProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string CardProjectName {
            get {
                return ResourceManager.GetString("CardProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string CardRank {
            get {
                return ResourceManager.GetString("CardRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cards Command Callback..
        /// </summary>
        public static string CardsAllCommandCallback {
            get {
                return ResourceManager.GetString("CardsAllCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards satisfied the search criteria..
        /// </summary>
        public static string CardSetIsEmpty {
            get {
                return ResourceManager.GetString("CardSetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards (%%project%%).
        /// </summary>
        public static string CardSetWindowTitle {
            get {
                return ResourceManager.GetString("CardSetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Stories (%%project%%).
        /// </summary>
        public static string CardSetWindowTitleStories {
            get {
                return ResourceManager.GetString("CardSetWindowTitleStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards for This User Command Callback..
        /// </summary>
        public static string CardsThisUserCommandCallback {
            get {
                return ResourceManager.GetString("CardsThisUserCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string CardVersion {
            get {
                return ResourceManager.GetString("CardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} - {1}.
        /// </summary>
        public static string CardWindowCaption {
            get {
                return ResourceManager.GetString("CardWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your settings.
        /// </summary>
        public static string CheckYourSettings {
            get {
                return ResourceManager.GetString("CheckYourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the field to edit its value.
        /// </summary>
        public static string ClickToEdit {
            get {
                return ResourceManager.GetString("ClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to make this transition.
        /// </summary>
        public static string ClickToMakeTransition {
            get {
                return ResourceManager.GetString("ClickToMakeTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Command Callback..
        /// </summary>
        public static string ExplorerCommandCallback {
            get {
                return ResourceManager.GetString("ExplorerCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThoughtWorks Explorer.
        /// </summary>
        public static string ExplorerViewCaption {
            get {
                return ResourceManager.GetString("ExplorerViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is closing and may include data that has not been submitted. Do you wish to proceed? Click No to return to the form..
        /// </summary>
        public static string FeedbackDataUnsubmittedWarning {
            get {
                return ResourceManager.GetString("FeedbackDataUnsubmittedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first fifty characters becomes the subject of this item in email..
        /// </summary>
        public static string FeedbackDescriptionToolTip {
            get {
                return ResourceManager.GetString("FeedbackDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback: Visual Studio Connector.
        /// </summary>
        public static string FeedbackEmailSubject {
            get {
                return ResourceManager.GetString("FeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string FeedbackFormCompanyLabel {
            get {
                return ResourceManager.GetString("FeedbackFormCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FeedbackFormDescriptionLabel {
            get {
                return ResourceManager.GetString("FeedbackFormDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string FeedbackFormEmailLabel {
            get {
                return ResourceManager.GetString("FeedbackFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThoughtWorks Visual Studio Connector Feedback.
        /// </summary>
        public static string FeedbackFormTitle {
            get {
                return ResourceManager.GetString("FeedbackFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FeedbackFormTitleLabel {
            get {
                return ResourceManager.GetString("FeedbackFormTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string FeedbackTypeDefect {
            get {
                return ResourceManager.GetString("FeedbackTypeDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Resuest.
        /// </summary>
        public static string FeedbackTypeFeature {
            get {
                return ResourceManager.GetString("FeedbackTypeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Results.
        /// </summary>
        public static string GoPipelinePropertiesCaption {
            get {
                return ResourceManager.GetString("GoPipelinePropertiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name cannot be empty.\n.
        /// </summary>
        public static string HostnameIsEmpty {
            get {
                return ResourceManager.GetString("HostnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name is malformed. The protocol must be either HTTP or HTTPS.\n.
        /// </summary>
        public static string InvalidProtocol {
            get {
                return ResourceManager.GetString("InvalidProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a reference to IVsOutputWindow.
        /// </summary>
        public static string IvsOutputWindowAccessFail {
            get {
                return ResourceManager.GetString("IvsOutputWindowAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name is malformed and must be like https://domain[:port] or http://domain[:port]\n.
        /// </summary>
        public static string MalformedHostnameVarious {
            get {
                return ResourceManager.GetString("MalformedHostnameVarious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murmur Accepted.
        /// </summary>
        public static string MessageMurmurCommitted {
            get {
                return ResourceManager.GetString("MessageMurmurCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2.
        /// </summary>
        public static string MingleApiSegment {
            get {
                return ResourceManager.GetString("MingleApiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Name&quot; field may not be blank or empty..
        /// </summary>
        public static string MingleCardNameNullOrEmpty {
            get {
                return ResourceManager.GetString("MingleCardNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards/&amp;&amp;card-no&amp;&amp;.
        /// </summary>
        public static string MingleCardSegment {
            get {
                return ResourceManager.GetString("MingleCardSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards.xml.
        /// </summary>
        public static string MingleCardSetSegment {
            get {
                return ResourceManager.GetString("MingleCardSetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Card Types..
        /// </summary>
        public static string MingleCardTypesLoadingError {
            get {
                return ResourceManager.GetString("MingleCardTypesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update attempt for this card has failed. The response received from the Mingle server is: [httpstatus].
        /// </summary>
        public static string MingleCardUpdateError {
            get {
                return ResourceManager.GetString("MingleCardUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Favorites..
        /// </summary>
        public static string MingleFavoritesLoadingError {
            get {
                return ResourceManager.GetString("MingleFavoritesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle or Go do not appear to be running. Try browsing to Mingle from a browser, then try this query again. This may also be caused by an errorneous URL for the Host or invalid credentials..
        /// </summary>
        public static string MingleNotRunning {
            get {
                return ResourceManager.GetString("MingleNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /projects.
        /// </summary>
        public static string MingleProjectsSegment {
            get {
                return ResourceManager.GetString("MingleProjectsSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Properties..
        /// </summary>
        public static string MinglePropertiesLoadingError {
            get {
                return ResourceManager.GetString("MinglePropertiesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Team members..
        /// </summary>
        public static string MingleTeamMembersLoadingError {
            get {
                return ResourceManager.GetString("MingleTeamMembersLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards/&amp;&amp;card-no&amp;&amp;/transitions.xml.
        /// </summary>
        public static string MingleTransitionSetSegment {
            get {
                return ResourceManager.GetString("MingleTransitionSetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Transitions..
        /// </summary>
        public static string MingleTransitionsLoadingError {
            get {
                return ResourceManager.GetString("MingleTransitionsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host url, login name and password are all required for connecting to Mingle. One of them is empty or null..
        /// </summary>
        public static string MissingMingleConnectionInformation {
            get {
                return ResourceManager.GetString("MissingMingleConnectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the user, password, host or project settings required for Mingle interaction appear to be missing or invalid. Would you like to edit them now?.
        /// </summary>
        public static string MissingOrInvalidCredentialData {
            get {
                return ResourceManager.GetString("MissingOrInvalidCredentialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setting is missing or invalid..
        /// </summary>
        public static string MissingOrInvalidSetting {
            get {
                return ResourceManager.GetString("MissingOrInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL paramater must be in the form &quot;/api/v2/[project]/... . Host name will be added by MingleServer..
        /// </summary>
        public static string MustBeMingleUrlSegment {
            get {
                return ResourceManager.GetString("MustBeMingleUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card.
        /// </summary>
        public static string NewCardDefaultName {
            get {
                return ResourceManager.GetString("NewCardDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the Mingle or Go. Some of the ThoughtWorks Exploer tree may not have been loaded. Please check your settings for a misspelled project name or similar issue..
        /// </summary>
        public static string OtherConnectionError {
            get {
                return ResourceManager.GetString("OtherConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a reference to the Output window General pane.
        /// </summary>
        public static string OutputWindowAccessFail {
            get {
                return ResourceManager.GetString("OutputWindowAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write on the Output window.
        /// </summary>
        public static string OutputWindowWriteFail {
            get {
                return ResourceManager.GetString("OutputWindowWriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package property is null..
        /// </summary>
        public static string PackageIsNull {
            get {
                return ResourceManager.GetString("PackageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem querying pipeline properties..
        /// </summary>
        public static string PipelineSearchError {
            get {
                return ResourceManager.GetString("PipelineSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (click on) a row in the list..
        /// </summary>
        public static string PleaseSelectRowFirst {
            get {
                return ResourceManager.GetString("PleaseSelectRowFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends Visual Studio to allow context-relevant connection to Mingle and GO..
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG-VSIX.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProjectId is null or empty. It is required..
        /// </summary>
        public static string ProjectIsRequired {
            get {
                return ResourceManager.GetString("ProjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property or field could not be updated..
        /// </summary>
        public static string PropertyCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("PropertyCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property is out of range, null or empty. A valid value is required..
        /// </summary>
        public static string PropertyOutOfRange {
            get {
                return ResourceManager.GetString("PropertyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Iteration).
        /// </summary>
        public static string PropertyValueCurrentIteration {
            get {
                return ResourceManager.GetString("PropertyValueCurrentIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string PropertyValueNotSet {
            get {
                return ResourceManager.GetString("PropertyValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select card....
        /// </summary>
        public static string PropertyValueSelectCard {
            get {
                return ResourceManager.GetString("PropertyValueSelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made settings changes that have not been saved. Would you like to save them, now?.
        /// </summary>
        public static string SettingsDataIsDirty {
            get {
                return ResourceManager.GetString("SettingsDataIsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitLabel {
            get {
                return ResourceManager.GetString("SubmitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be serializable..
        /// </summary>
        public static string TheTypeMustBeSerializable {
            get {
                return ResourceManager.GetString("TheTypeMustBeSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment in the box below and close this form..
        /// </summary>
        public static string TransitionAdmonitionLabel {
            get {
                return ResourceManager.GetString("TransitionAdmonitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transition could not be applied..
        /// </summary>
        public static string TransitionCannotBeApplied {
            get {
                return ResourceManager.GetString("TransitionCannotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a comment for this transition. Do you wish to supply a comment?.
        /// </summary>
        public static string TransitionCommentRequired {
            get {
                return ResourceManager.GetString("TransitionCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition = .
        /// </summary>
        public static string TransitionEquals {
            get {
                return ResourceManager.GetString("TransitionEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a transition..
        /// </summary>
        public static string TransitionIsNull {
            get {
                return ResourceManager.GetString("TransitionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Comment.
        /// </summary>
        public static string TransitionWindowTitle {
            get {
                return ResourceManager.GetString("TransitionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle/Go Settings Command Callback..
        /// </summary>
        public static string TwSettingsCommandCallback {
            get {
                return ResourceManager.GetString("TwSettingsCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url property is null or empty..
        /// </summary>
        public static string UrlPropertyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("UrlPropertyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view is not available in Visual Studio..
        /// </summary>
        public static string ViewNotUsableFromVisualStudio {
            get {
                return ResourceManager.GetString("ViewNotUsableFromVisualStudio", resourceCulture);
            }
        }
    }
}
